name: Manual Release

on:
  workflow_dispatch:
    inputs:
      version:
        required: false
        type: string

jobs:
  ci:
    uses: ./.github/workflows/ci.yml

  e2e:
    uses: ./.github/workflows/e2e.yml

  publish-server:
    needs: [ci, e2e]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Build project artifacts
        id: build
        uses: ./.github/actions/build-sharkord
        with:
          version: ${{ inputs.version }}

      - name: Build and publish Docker image
        uses: ./.github/actions/docker-build-publish
        with:
          docker_registry: ghcr.io
          docker_username: ${{ github.repository_owner }}
          docker_password: ${{ secrets.GITHUB_TOKEN }}
          images: ghcr.io/${{ github.repository }}
          tags: |
            latest
            ${{ steps.build.outputs.version }}
          labels: |
            org.opencontainers.image.title=Sharkord
            org.opencontainers.image.description=Sharkord Server
            org.opencontainers.image.version=${{ github.event.release.name }}
            org.opencontainers.image.source=https://github.com/${{ github.repository_owner }}/sharkord

      - name: Upload Artifacts to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.sha }}
          name: v${{ steps.build.outputs.version }}
          draft: true
          files: |
            apps/server/build/out/sharkord-*

  publish-desktop:
    needs: [ci, e2e]
    runs-on: ${{ matrix.os }}
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Build desktop artifacts
        id: build
        uses: ./.github/actions/build-desktop
        with:
          version: ${{ inputs.version }}

      - name: Upload Artifacts to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.sha }}
          name: v${{ steps.build.outputs.version }}
          draft: true
          files: |
            apps/desktop/build/out/*.exe
            apps/desktop/build/out/*.blockmap
            apps/desktop/build/out/*.AppImage
            apps/desktop/build/out/latest*.yml
